#!/bin/bash

# To autostart by cron:
# ------------------------
# sudo crontab -e
#
# And add a line:
# ------------------------
# */2 * * * * /bin/bash /var/www/DigiAssetDividends/check-run-api


URL=127.0.0.1:60001
WORKDIR=/var/www/DigiAssetDividends/node
LOGFILE=/var/www/tick-dad.log

cd $WORKDIR
date >> $LOGFILE

# Check it
`curl --silent --output /dev/null "$URL"`
if [ "$?" = "7" ]; then
    echo "running dad..." >> $LOGFILE
    node --abort-on-uncaught-exception ./app.js dad >> $LOGFILE &
    sleep 3
    exit 1
fi

echo "dad - ok" >> $LOGFILE
exit 0
