#!/bin/bash

# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

# Install requierements
npm install

# Compile weak-napi
cd node_modules/weak-napi/build
make
